services:
  app:
    image: golang:1.23-alpine  # Usamos la imagen oficial de Golang
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./scripts:/app/scripts
    environment:
      - DATABASE_URL=sqlite:///tmp/tarot.db
      - HUGGINGFACE_API_KEY=$HUGGINGFACE_API_KEY
      - USE_HUGGINGFACE=$USE_HUGGINGFACE
    working_dir: /app
    command: sh -c "apk add --no-cache sqlite gcc musl-dev && sh /app/scripts/init_db.sh && export CGO_ENABLED=1 && go run main.go"